Enviando request

diff --git a/.github/workflows/request.yml b/.github/workflows/request.yml
--- a/.github/workflows/request.yml
+++ b/.github/workflows/request.yml
@@ -9,7 +9,62 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Sending request
+
+      - name: Sending correct request
+        run: |
+            response='{
+                "author": {
+                "accountId": "5b10a2844c20165700ede21g",
+                "active": false,
+                "displayName": "Mia Krystof",
+                "self": "https://your-domain.atlassian.net/rest/api/3/user?accountId=5b10a2844c20165700ede21g"
+                },
+                "body": {
+                "type": "doc",
+                "version": 1,
+                "content": [
+                    {
+                    "type": "paragraph",
+                    "content": [
+                        {
+                        "type": "text",
+                        "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget venenatis elit. Duis eu justo eget augue iaculis fermentum. Sed semper quam laoreet nisi egestas at posuere augue semper."
+                        }
+                    ]
+                    }
+                ]
+                },
+                "created": "2021-01-17T12:34:00.000+0000",
+                "id": "10000",
+                "self": "https://your-domain.atlassian.net/rest/api/3/issue/10010/comment/10000",
+                "updateAuthor": {
+                "accountId": "5b10a2844c20165700ede21g",
+                "active": false,
+                "displayName": "Mia Krystof",
+                "self": "https://your-domain.atlassian.net/rest/api/3/user?accountId=5b10a2844c20165700ede21g"
+                },
+                "updated": "2021-01-18T23:45:00.000+0000",
+                "visibility": {
+                "identifier": "Administrators",
+                "type": "role",
+                "value": "Administrators"
+                }
+            }'
+            echo "$response"
+            
+            error_messages=$(echo "$response" | jq -r '.errorMessages[]')
+            
+            # Condicional para determinar si hay un error
+            if [ -z "$error_messages" ]; then
+                # No hay error_messages, imprime "Ejecución exitosa"
+                echo "Ejecución exitosa"
+                exit 0
+            else
+                # Hay un error_messages, imprime el mensaje
+                echo "Error: $error_messages"
+                exit 1
+            fi
+      - name: Sending request failed
         run: | 
             yes | sudo apt-get install jq
 
